name: Manually triggered deploy

on:
  workflow_dispatch:
    inputs:
      is_approved:
        description: 'Would you start the deployment?'
        required: true
        default: '0'
      timestamp:
        description: 'Slack message timestamp'
        required: false

env:
  SLACK_CHANNEL: "#test-bot" # Slack Channel name or ID
  SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }} # Slack API Token
          
jobs:
  php_deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Approved
        if: ((github.event.inputs.is_approved == 1))
        run: |
          echo "Deploy have been approved and will start."
      - name: Deploy Denied
        if: ((github.event.inputs.is_approved == 0))
        run: |
          echo "Deploy have been denied."
      - name: Deploy Status Message
        if: failure()
        env:
          TITLE: "GitHub Deploy Success"
          PROJECT_NAME: "PHP-CICD"
          ISSUE_ID: "5476"
          BUILD_STATUS: "PASS"
          TEST_STATUS: "PASS"
          DEPLOY_STATUS: "PASS"
        run: |
          pip3 install -U pip setuptools
          python3 scripts/slack_chatops_post.py
      - name: Deploy Failure Handler
        if: failure()
        env:
          MESSAGE_TYPE: "ERROR"
          TITLE: "GitHub Workflow Error"
          PROJECT_NAME: "PHP-CICD"
          ISSUE_ID: "5476"
          BUILD_STATUS: "PASS"
          TEST_STATUS: "PASS"
          DEPLOY_STATUS: "FAIL"
        run: |
                    pip3 install slackclient
          python3 scripts/slack_chatops_post.py
