name: Manually triggered deploy

on:
  workflow_dispatch:
    inputs:
      is_approved:
        description: 'Would you start the deployment?'
        required: true
        default: '0'
      timestamp:
        description: 'Slack message timestamp'
        required: false
      channel:
        description: 'Slack message channel'
        required: false

env:
  SLACK_CHANNEL: ${{ github.event.inputs.channel }} # Slack Channel name or ID
  SLACK_TIMESTAMP: ${{ github.event.inputs.timestamp }}
  PROJECT_NAME: "PHP-CICD"
  ISSUE_ID: "5476"
  BUILD_STATUS: "PASS"
  TEST_STATUS: "PASS"
          
jobs:
  php_deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Deploy Approved
        if: ((github.event.inputs.is_approved == 1))
        run: |
          echo "Deploy have been approved and will start."
          curl --location --request POST 'https://slack.toumoro.com/github/${env.SLACK_CHANNEL}/${env.PROJECT_NAME}/${env.GITHUB_REF////%2F}/${env.GITHUB_RUN_ID}/deploy/status' \
            --header 'Content-Type: application/json' \
            --data-raw '{
                "status": [
                    {
                        "name": "Build",
                        "status": "PASS"
                    },
                    {
                        "name": "Tests",
                        "status": "PASS"
                    },
                    {
                        "name": "Deploy",
                        "status": "PASS"
                    },
                ],
                "issue_id": "${env.ISSUE_ID}",
                "github_actor": "${env.GITHUB_ACTOR}",
                "slack_timestamp": "${env.SLACK_TIMESTAMP}",
                "github_repository": "${env.GITHUB_REPOSITORY}"
            }'
      - name: Deploy Denied
        if: ((github.event.inputs.is_approved == 0))
        run: |
          echo "Deploy have been denied."
          curl --location --request POST 'https://slack.toumoro.com/github/${env.SLACK_CHANNEL}/${env.PROJECT_NAME}/${env.GITHUB_REF////%2F}/${env.GITHUB_RUN_ID}/deploy/status' \
            --header 'Content-Type: application/json' \
            --data-raw '{
                "status": [
                    {
                        "name": "Build",
                        "status": "PASS"
                    },
                    {
                        "name": "Tests",
                        "status": "PASS"
                    },
                    {
                        "name": "Deploy",
                        "status": "FAIL"
                    },
                ],
                "issue_id": "${env.ISSUE_ID}",
                "github_actor": "${env.GITHUB_ACTOR}",
                "slack_timestamp": "${env.SLACK_TIMESTAMP}",
                "github_repository": "${env.GITHUB_REPOSITORY}"
            }'
      - name: Deploy Failure Handler
        if: failure()
        env:
          TITLE: "GitHub Workflow Error"
          MESSAGE_TYPE: "ERROR"
          DEPLOY_STATUS: "FAIL"
        run: |
          curl --location --request POST 'https://slack.toumoro.com/github/${env.SLACK_CHANNEL}/${env.PROJECT_NAME}/${env.GITHUB_REF////%2F}/${env.GITHUB_RUN_ID}/deploy/error' \
            --header 'Content-Type: application/json' \
            --data-raw '{
                "status": [
                    {
                        "name": "Build",
                        "status": "PASS"
                    },
                    {
                        "name": "Tests",
                        "status": "PASS"
                    },
                    {
                        "name": "Deploy",
                        "status": "FAIL"
                    },
                ],
                "issue_id": "${env.ISSUE_ID}",
                "github_actor": "${env.GITHUB_ACTOR}",
                "slack_timestamp": "${env.SLACK_TIMESTAMP}",
                "github_repository": "${env.GITHUB_REPOSITORY}"
            }'
