name: Manually triggered deploy

on:
  workflow_dispatch:
    inputs:
      is_approved:
        description: 'Would you start the deployment?'
        required: true
        default: '0'

jobs:
  php_deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Approved
        if: ((github.event.inputs.is_approved != 0))
        run: |
          echo "Deploy have been approved and will start."
      - name: Deploy Denied
        if: !((github.event.inputs.is_approved))
        run: |
          echo "Deploy have been denied."
      - name: Deploy Failure Handler
        if: failure()
        run: |
          chmod +x ./scripts/on_deploy_failure.sh
          sh ./scripts/on_deploy_failure.sh
