name: Manually triggered deploy

on:
  workflow_dispatch:
    inputs:
      is_approved:
        description: 'Would you start the deployment?'
        required: true
        default: '0'
      timestamp:
        description: 'Slack message timestamp'
        required: false
      channel:
        description: 'Slack message channel'
        required: false

env:
  SLACK_CHANNEL: ${{ github.event.inputs.channel }} # Slack Channel name or ID
  SLACK_TIMESTAMP: ${{ github.event.inputs.timestamp }}
  PROJECT_NAME: "PHP-CICD"
  ISSUE_ID: "5476"
  API_KEY: ${{ secrets.API_KEY }}
  API_URL: ${{ secrets.API_URL }}
          
jobs:
  php_deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Deploy Approved
        if: ((github.event.inputs.is_approved == 1))
        uses: docker://kerberosmorphy/toumoro-slack-messaging:latest
        with:
          api_url: ${{ env.API_URL }}
          api_key: ${{ env.API_KEY }}
          service: github
          project: ${{ env.PROJECT_NAME }}
          channel: ${{ env.SLACK_CHANNEL}}
          ref: ${{ github.ref }}
          run_id: ${{ github.run_id }}
          step: Deploy
          type: status
          status: Build:FAIL;Test:PASS;Deploy:PASS
          issue_id: ${{ env.ISSUE_ID }}
          actor: ${{ github.actor }}
          repository: ${{ github.repository }}
          verbose: '2'
      - name: Deploy Denied
        if: ((github.event.inputs.is_approved == 0))
        uses: docker://kerberosmorphy/toumoro-slack-messaging:latest
        with:
          api_url: ${{ env.API_URL }}
          api_key: ${{ env.API_KEY }}
          service: github
          project: ${{ env.PROJECT_NAME }}
          channel: ${{ env.SLACK_CHANNEL}}
          ref: ${{ github.ref }}
          run_id: ${{ github.run_id }}
          step: Deploy
          type: status
          status: Build:FAIL;Test:PASS;Deploy:FAIL
          issue_id: ${{ env.ISSUE_ID }}
          actor: ${{ github.actor }}
          repository: ${{ github.repository }}
          verbose: '2'
      - name: Deploy Failure Handler
        if: failure()
        uses: docker://kerberosmorphy/toumoro-slack-messaging:latest
        with:
          api_url: ${{ env.API_URL }}
          api_key: ${{ env.API_KEY }}
          service: github
          project: ${{ env.PROJECT_NAME }}
          channel: ${{ env.SLACK_CHANNEL}}
          ref: ${{ github.ref }}
          run_id: ${{ github.run_id }}
          step: Deploy
          type: error
          status: Build:FAIL;Test:PASS;Deploy:FAIL
          issue_id: ${{ env.ISSUE_ID }}
          actor: ${{ github.actor }}
          repository: ${{ github.repository }}
          verbose: '2'
